spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE-ID
            client-secret: GOOGLE-SECRET
            scope:
              - email
              - profile
          facebook:
            client-id: FACEBOOK-ID
            client-secret: FACEBOOK-SECRET
            scope:
              - email
              - public_profile
          github:
            client-id: GITHUB-ID
            client-secret: GITHUB-SECRET
            scope:
              - user:email
              - read:user
  mail:
    host: smtp.gmail.com
    username: cabin.escape.room.web.app@gmail.com
    password: GMAIL SECRET
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true