spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 164734010234-617v0287clqcr4flkdhnei2abmqk1d7r.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 848955616546678
            clientSecret: 1d96d49c11f9771f79abb50cc965cbac
            scope:
              - email
              - public_profile
          github:
            clientId: 64e12d8f06db2cd503c3
            clientSecret: 5a01906487a60ea1d7da55f95d0f1b48fbcd19b0
            scope:
              - user:email
              - read:user