spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 164734010234-617v0287clqcr4flkdhnei2abmqk1d7r.apps.googleusercontent.com
            clientSecret: GOOGLE SECRET
            scope:
              - email
              - profile
          facebook:
            clientId: 848955616546678
            clientSecret: FACEBOOK SECRET
            scope:
              - email
              - public_profile
          github:
            clientId: 64e12d8f06db2cd503c3
            clientSecret: GITHUB SECRET
            scope:
              - user:email
              - read:user